services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: wildwest-node
    restart: always
    ports:
      - "3000:3000"
    networks:
      - wildwest-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: wildwest-nginx
    restart: always
    depends_on:
      - node
    ports:
      - "8087:80"
    networks:
      - wildwest-net

networks:
  wildwest-net:
    driver: bridge